name: flutter_secure_storage
description: Secure Storage plugin for Flutter.
version: 0.0.1
author: German Saprykin <saprykin.h@gmail.com>
homepage: https://github.com/mogol/flutter_secure_storage

flutter:
  plugin:
    androidPackage: com.it_nomads.fluttersecurestorage
    pluginClass: FlutterSecureStoragePlugin

dependencies:
  flutter:
    sdk: flutter
